# Generated by Django 5.0.4 on 2024-04-12 07:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('billing_receipt_type', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Доставка', max_length=100, verbose_name='Вид получения товара')),
                ('payment_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код оплаты биллинга')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговая сумма')),
                ('delivery_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость доставки')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания биллинга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Биллинг',
                'verbose_name_plural': 'Биллинги',
            },
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Отчет продажа товар',
                'verbose_name_plural': 'Отчеты продажи товаров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billing',),
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('configurator', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Значения атрибута конфигуратора товара')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Итоговая цена товара')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_products', to='billing.billing', verbose_name='Биллинг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_billings', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продукт биллинга',
                'verbose_name_plural': 'Продукты биллингов',
            },
        ),
    ]
